In [1]:
mylist=[1,2,3]

In [1]:
import numpy as np

In [5]:
array= np.array(mylist)

In [6]:
array

array([1, 2, 3])

In [7]:
mymat= [[1,2,3],[4,5,6],[7,8,9]]

In [8]:
mymat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [9]:
np.array(mymat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [21]:
np.zeros(4)

array([0., 0., 0., 0.])

In [31]:
np.zeros((3,4,5))

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [27]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [28]:
np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [30]:
1+10/11


1.9090909090909092

In [33]:
np.eye(4)[1]

array([0., 1., 0., 0.])

In [41]:
np.random.randn(5)

array([-0.5855927 , -0.87816424,  0.89977381, -0.60090834, -0.52422474])

In [5]:
np.random.randint(10:,10)

SyntaxError: invalid syntax (<ipython-input-5-c88bf25c2567>, line 1)

In [44]:
arr=np.arange(16)

In [45]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [10]:
ranarr=np.random.randint(1,50,10)

In [12]:
ranarr

array([48, 36, 13,  5, 20, 27,  2,  7,  6,  4])

In [13]:
ranarr[3:]

array([ 5, 20, 27,  2,  7,  6,  4])

In [50]:
arr.reshape(4,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [54]:

arr.argmax()

15

In [56]:
arr.argmin()

0

In [57]:
arr.shape

(16,)

In [58]:
arr=arr.reshape(4,4)

In [59]:
arr.shape

(4, 4)

In [60]:
arr.dtype


dtype('int32')

In [61]:
from numpy.random import randint

In [62]:
randint(1,10,2)

array([7, 5])

In [14]:
#Indexing and Selection

In [15]:
import numpy as np

In [21]:
arr=np.arange(1,11)

In [27]:
arr[9]

10

In [33]:
arr[5:]

array([ 6,  7,  8,  9, 10])

In [34]:
arr[:5]=20

In [35]:
arr

array([20, 20, 20, 20, 20,  6,  7,  8,  9, 10])

In [36]:
arr=np.arange(0,11)

In [37]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [38]:
arr_slice=arr[0:5]

In [40]:
arr_slice

array([0, 1, 2, 3, 4])

In [42]:
arr_slice[:]=100

In [43]:
arr_slice

array([100, 100, 100, 100, 100])

In [44]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [45]:
arr=np.arange(0,11)

In [46]:
arr_copy=arr.copy()

In [47]:
arr_copy[:]=10

In [48]:
arr_copy

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10])

In [49]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

 array remains unchanged when copy() is used, else it overwrites due to space constraints 

In [50]:
#Creating a 2-D array

In [51]:
arr_2d=np.array([[5,10,15],[20,25,30],[35,40,45]])

In [53]:
arr_2d[2][2]

45

In [56]:
arr_2d[2,2]

45

Same as double bracket method

In [62]:
arr_2d[:1,1:]

array([[10, 15]])

In [63]:
arr=np.arange(1,11)

In [65]:
bool_arr=arr>4

In [66]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [67]:
arr[arr>4]

array([ 5,  6,  7,  8,  9, 10])

In [68]:
arr_2dim=np.arange(25).reshape(5,5)

In [78]:
arr_2dim[2:4,1:3]

array([[11, 12],
       [16, 17]])

In [79]:
arr=np.arange(0,11)

In [81]:
arr+arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [82]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [83]:
arr-arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [84]:
arr*arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [85]:
 arr/arr

c:\users\gayat\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [86]:
1/arr

c:\users\gayat\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111,
       0.1       ])

In [88]:
arr**3

array([   0,    1,    8,   27,   64,  125,  216,  343,  512,  729, 1000],
      dtype=int32)

In [89]:
arr


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [90]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [91]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [92]:
np.max(arr)

10

In [95]:
np.tan(arr)

array([ 0.        ,  1.55740772, -2.18503986, -0.14254654,  1.15782128,
       -3.38051501, -0.29100619,  0.87144798, -6.79971146, -0.45231566,
        0.64836083])

In [96]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [97]:
np.log(arr)

c:\users\gayat\appdata\local\programs\python\python37\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

In [5]:
n,p=[int(x) for x in input().split()]

2 3


In [11]:
lst=[]
for i in range(n):
    for j in range(p):
        lst.append(int(input()))

2
3
5
6
7
8


In [12]:
lst

[2, 3, 5, 6, 7, 8]

In [13]:
arr=np.array(lst)

In [16]:
arr.reshape(n,p)

array([[2, 3, 5],
       [6, 7, 8]])

In [20]:
for i in range(n):
    print(arr[i].mean())

2.0
3.0


In [22]:
print(arr.mean(axis=1))

AxisError: axis 1 is out of bounds for array of dimension 1